# Generated by Django 5.1.3 on 2024-11-16 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
